# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 597a3d3f7df8e1c5f9f166b797b6079c3a79fd83f868589234afe67665ec06d6c55f1dfd1a291ebe47ed8ee1168e277430e5ba99c08c3f774c89146bb68b7e29

test:
  secret_key_base: 7db51e6b3387c2a997e7a4a254a0a6097bf0f0bd572df3dafd3f964f4c28f088a494e9906122a58eeaedf4bbb74ff2cd5d9bcfc8d2ed1f3ed699914b5d15c3a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
